### ISSUE TITLE
merge 的时候是不是要跳过一些无效的 entry？

### ISSUE THREAD

**Issue by binderclip** [elliotchenzichang/tiny-bitcask#1]
这里读到 entry 之后是不是检查一下是否删除状态，以及和内存中的 index 相比是不是老数据，如果是老数据的话应该就不用写入了？  
好像没看到相关的判断逻辑。

https://github.com/elliotchenzichang/tiny-bitcask/blob/master/db.go#L104-L114

```go
entry, err := db.s.readEntry(fid, off)
if err == nil {
	off += int64(entry.Size())
	oldIndex := db.kd.index[string(entry.key)]
	if oldIndex.fid == fid && oldIndex.off == off {
    	newIndex, err := db.s.writeAt(entry.Encode())
    	if err != nil {
        	return err
    	}
    	db.kd.index[string(entry.key)] = newIndex
	}
}
```

**Comment by elliotchenzichang** [comment]
其实是不需要的，内存索引中存的永远是最新数据的位置，Merge的时候拿到的数据如果是最新的，也就是和内存索引中的一样，这时候重新写入这条数据，重新写入之后这条数据就变成了旧数据，等这个文件的所有数据都重新写入了，这个文件的所有数据就都是老数据了，然后把整个文件删除。
所以Delete数据的时候有一个关键的地方就是，删除这个数据的内存索引，在这里：https://github.com/elliotchenzichang/tiny-bitcask/blob/3f293851184b4eede34d64625abfc63232f75912/db.go#L86，
然后你刚说的场景我刚提交了个测试用例：https://github.com/elliotchenzichang/tiny-bitcask/blob/3f293851184b4eede34d64625abfc63232f75912/db_test.go#L86
是没问题的。
