### ISSUE TITLE
关于demo分支一个小细节的疑问

### ISSUE THREAD

**Issue by yanyyi** [elliotchenzichang/tiny-bitcask#14]
tiny-bitcask仓库的demo分支：stroage.go:121， path := fmt.Sprintf("%s/%d", s.dir, fid)是否少了文件后缀名，之后调用os.OpenFile应该会失败吧。

**Comment by elliotchenzichang** [comment]
hi, 不好意思来晚了，确实是这样，已经改过来了，感谢issue。

**Comment by yanyyi** [comment]
好的
